"""

Revision ID: 58a6de8c5ca8
Revises: 
Create Date: 2024-05-26 19:03:49.459431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a6de8c5ca8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_association',
    sa.Column('photo_id', sa.BigInteger(), nullable=False),
    sa.Column('association_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], ),
    sa.PrimaryKeyConstraint('photo_id', 'association_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_association')
    op.drop_table('associations')
    # ### end Alembic commands ###
